spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    mode: html
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 10m

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    cacheEnabled: true
    lazyLoadingEnabled: true

mybatis-plus:
  type-aliases-package: com.xuchen.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
  global-config:
    capital-mode: true
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: info
  file: logs/BootManage.log

defaultPwd: 123456